import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { getUserFromRequest } from '@/lib/auth';
import { errorResponse, successResponse, handleApiError } from '@/lib/api-utils';
import { withAuth, withRateLimit, withValidation } from '@/middleware/apiAuth';
import { z } from 'zod';

// Validation schema for student linking
const linkStudentSchema = z.object({
  studentId: z.string().min(1, 'Student ID is required'),
  verificationCode: z.string().min(6, 'Verification code must be at least 6 characters'),
  relationshipType: z
    .enum(['PARENT', 'GUARDIAN', 'OTHER'])
    .default('PARENT')
    .optional(),
});

type LinkStudentRequest = z.infer<typeof linkStudentSchema>;

/**
 * POST /api/guardian/link-student
 * 
 * Allows a guardian to link a student by entering a verification code
 * generated by an admin/facilitator
 * 
 * Request body:
 * {
 *   "studentId": "student-id",
 *   "verificationCode": "ABCD1234",
 *   "relationshipType": "PARENT" // Optional: PARENT, GUARDIAN, or OTHER
 * }
 */
async function linkStudentHandler(request: NextRequest) {
  try {
    const user = await getUserFromRequest(request);

    if (!user) {
      return errorResponse('Unauthorized', 401);
    }

    if (user.role !== 'GUARDIAN') {
      return errorResponse('Forbidden: User is not a guardian', 403);
    }

    const body = await request.json();
    const validatedData = linkStudentSchema.parse(body);

    const { studentId, verificationCode, relationshipType = 'PARENT' } = validatedData;

    // Verify student exists
    const student = await prisma.student.findUnique({
      where: { id: studentId },
      select: {
        id: true,
        firstName: true,
        lastName: true,
        status: true,
      },
    });

    if (!student) {
      return errorResponse('Student not found', 404);
    }

    if (student.status === 'INACTIVE') {
      return errorResponse('Cannot link to an inactive student', 400);
    }

    // Check if relationship already exists
    const existingRelationship = await prisma.guardianStudent.findUnique({
      where: {
        guardianId_studentId: {
          guardianId: user.userId,
          studentId,
        },
      },
    });

    if (existingRelationship) {
      return errorResponse(
        `Guardian relationship already ${existingRelationship.isVerified ? 'verified' : 'pending'} verification`,
        400
      );
    }

    // Verify the verification code
    // The code should match a code generated by an admin/facilitator
    // For now, we'll do a simple check - in production, this could be more sophisticated
    // The code might be stored temporarily with an expiration time
    
    // For demonstration, we'll accept the code if it's alphanumeric and at least 6 chars
    // In a real implementation, there would be a VerificationCode model with expiration
    if (!verificationCode || verificationCode.length < 6) {
      return errorResponse('Invalid verification code format', 400);
    }

    // TODO: Verify code against VerificationCode model with expiration check
    // For now, accept any valid code format - this should be enhanced with:
    // - VerificationCode model in schema
    // - Code generation endpoint for admins
    // - Code expiration (e.g., 24 hours)
    // - Single-use codes

    // Create the guardian-student relationship (initially unverified)
    const guardianStudent = await prisma.guardianStudent.create({
      data: {
        guardianId: user.userId,
        studentId,
        relationshipType,
        verificationCode, // Store for reference/audit
        isVerified: true, // In production, this might be false until admin verifies
        verifiedAt: new Date(),
      },
      select: {
        id: true,
        student: {
          select: {
            id: true,
            firstName: true,
            lastName: true,
          },
        },
        relationshipType: true,
        isVerified: true,
        createdAt: true,
      },
    });

    return successResponse({
      guardianStudent: {
        id: guardianStudent.id,
        student: {
          id: guardianStudent.student.id,
          name: `${guardianStudent.student.firstName} ${guardianStudent.student.lastName}`,
        },
        relationshipType: guardianStudent.relationshipType,
        verified: guardianStudent.isVerified,
        linkedAt: guardianStudent.createdAt,
      },
    });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return errorResponse(
        `Validation error: ${error.errors.map((e) => e.message).join(', ')}`,
        400
      );
    }
    return handleApiError(error);
  }
}

export const POST = withAuth(
  withRateLimit(
    withValidation(linkStudentHandler, linkStudentSchema),
    'moderate'
  ),
  ['GUARDIAN']
);
