/**
 * Automated Intervention System
 * 
 * Automatically creates interventions when students are flagged as high-risk:
 * - Creates FacilitatorTask for check-in calls
 * - Sends notifications to coordinators
 * - Suggests curriculum resources
 * - Tracks intervention effectiveness
 */

import { PrismaClient } from '@prisma/client';
import { RiskAssessment, RiskFactor } from './riskAnalysis';

const prisma = new PrismaClient();

export interface Intervention {
  id: string;
  type: 'TASK' | 'NOTIFICATION' | 'RESOURCE';
  studentId: string;
  riskProfileId: string;
  status: 'PENDING' | 'COMPLETED' | 'DISMISSED';
  details: Record<string, any>;
  createdAt: Date;
}

/**
 * Create a facilitator task for high-risk student check-in
 */
export async function createCheckInTask(
  studentId: string,
  groupId: string,
  riskLevel: string,
  riskFactors: RiskFactor[]
): Promise<string> {
  const student = await prisma.student.findUnique({
    where: { id: studentId },
    select: { firstName: true, lastName: true },
  });

  if (!student) {
    throw new Error('Student not found');
  }

  const studentName = `${student.firstName} ${student.lastName}`;

  // Build description from risk factors
  const factorDescriptions = riskFactors
    .slice(0, 3)
    .map((f) => `- ${f.description}`)
    .join('\n');

  const description = `🚨 HIGH RISK ALERT

Student: ${studentName}
Risk Level: ${riskLevel}

Key Risk Factors:
${factorDescriptions}

Action Required:
1. Schedule immediate one-on-one check-in call
2. Discuss barriers to success (attendance, understanding, personal issues)
3. Create personalized support plan
4. Follow up within 7 days

This task was automatically generated by the Early Warning System based on behavioral patterns.`;

  // Set due date to 2 days from now for urgent tasks
  const dueDate = new Date();
  dueDate.setDate(dueDate.getDate() + 2);

  const task = await prisma.facilitatorTask.create({
    data: {
      title: `🚨 Urgent: Check-in with ${studentName} (High Risk)`,
      description,
      dueDate,
      groupId,
      completed: false,
    },
  });

  return task.id;
}

/**
 * Send notification to coordinator about high-risk student
 */
export async function notifyCoordinator(
  studentId: string,
  groupId: string,
  riskLevel: string,
  riskFactors: RiskFactor[]
): Promise<void> {
  // Get student and group info
  const student = await prisma.student.findUnique({
    where: { id: studentId },
    include: {
      group: {
        select: {
          name: true,
          coordinator: true,
          contactName: true,
        },
      },
      facilitator: {
        select: {
          name: true,
          email: true,
        },
      },
    },
  });

  if (!student) {
    throw new Error('Student not found');
  }

  const studentName = `${student.firstName} ${student.lastName}`;

  // Build notification message
  const message = {
    type: 'HIGH_RISK_ALERT',
    severity: 'HIGH',
    title: `Student at High Risk: ${studentName}`,
    body: `${studentName} in ${student.group.name} has been flagged as HIGH RISK by the Early Warning System.\n\n` +
          `Risk Factors:\n${riskFactors.slice(0, 3).map(f => `• ${f.description}`).join('\n')}\n\n` +
          `Facilitator ${student.facilitator.name} has been notified to schedule an immediate check-in.`,
    studentId: student.id,
    groupId: student.groupId,
    facilitatorId: student.facilitatorId,
    timestamp: new Date(),
    data: {
      riskLevel,
      riskFactorCount: riskFactors.length,
      coordinatorEmail: student.group.coordinator || student.group.contactName,
    },
  };

  // Log to audit trail
  await prisma.auditLog.create({
    data: {
      userId: 'SYSTEM',
      action: 'HIGH_RISK_NOTIFICATION_SENT',
      entityType: 'Student',
      entityId: studentId,
      timestamp: new Date(),
      ipAddress: '127.0.0.1',
      metadata: JSON.stringify(message),
    },
  });

  // In production, this would integrate with email/SMS service
  console.log('[NOTIFICATION] Coordinator notified:', message);

  // TODO: Integrate with email service (Resend, SendGrid, etc.)
  // await sendEmail({
  //   to: student.group.coordinator,
  //   subject: message.title,
  //   body: message.body,
  // });
}

/**
 * Suggest curriculum resources based on risk factors
 */
export async function suggestResources(
  studentId: string,
  riskFactors: RiskFactor[]
): Promise<string[]> {
  const student = await prisma.student.findUnique({
    where: { id: studentId },
    include: {
      currentModule: {
        include: {
          documents: true,
        },
      },
    },
  });

  if (!student || !student.currentModule) {
    return [];
  }

  const resources: string[] = [];

  // Analyze risk factors and suggest targeted resources
  for (const factor of riskFactors) {
    if (factor.category === 'ASSESSMENT') {
      // Suggest study materials and practice assessments
      resources.push(
        `📚 Review ${student.currentModule.name} study materials`,
        `✍️ Complete additional practice formatives for weak areas`,
        `👥 Schedule peer study session with high-performing students`
      );

      // Find relevant curriculum documents
      const docs = student.currentModule.documents
        .filter((d) => d.category === 'STUDY_GUIDE' || d.category === 'PRACTICE')
        .slice(0, 2);

      docs.forEach((doc) => {
        resources.push(`📄 ${doc.title}`);
      });
    } else if (factor.category === 'ATTENDANCE') {
      resources.push(
        `📞 Contact student to discuss attendance barriers`,
        `🚌 Review transport options or schedule flexibility`,
        `💼 Check workplace placement requirements if applicable`
      );
    } else if (factor.category === 'ENGAGEMENT') {
      resources.push(
        `💡 Introduce gamification or interactive learning activities`,
        `👁️ Show real-world application of current module content`,
        `🎯 Set short-term achievable goals to rebuild motivation`
      );
    }
  }

  // Remove duplicates
  return Array.from(new Set(resources));
}

/**
 * Main function to trigger all interventions for a high-risk student
 */
export async function triggerInterventions(
  studentId: string,
  riskProfileId: string,
  assessment: RiskAssessment
): Promise<{
  taskId?: string;
  notificationSent: boolean;
  resources: string[];
}> {
  const student = await prisma.student.findUnique({
    where: { id: studentId },
    select: { groupId: true, firstName: true, lastName: true },
  });

  if (!student) {
    throw new Error('Student not found');
  }

  const results = {
    taskId: undefined as string | undefined,
    notificationSent: false,
    resources: [] as string[],
  };

  try {
    // Only trigger for HIGH risk students
    if (assessment.riskLevel === 'HIGH') {
      // 1. Create facilitator task
      results.taskId = await createCheckInTask(
        studentId,
        student.groupId,
        assessment.riskLevel,
        assessment.riskFactors
      );

      // 2. Notify coordinator
      await notifyCoordinator(
        studentId,
        student.groupId,
        assessment.riskLevel,
        assessment.riskFactors
      );
      results.notificationSent = true;

      // 3. Suggest resources
      results.resources = await suggestResources(studentId, assessment.riskFactors);

      // Log intervention creation
      await prisma.auditLog.create({
        data: {
          userId: 'SYSTEM',
          action: 'AUTO_INTERVENTION_TRIGGERED',
          entityType: 'StudentRiskProfile',
          entityId: riskProfileId,
          timestamp: new Date(),
          ipAddress: '127.0.0.1',
          metadata: JSON.stringify({
            studentId,
            riskLevel: assessment.riskLevel,
            taskCreated: !!results.taskId,
            notificationSent: results.notificationSent,
            resourceCount: results.resources.length,
          }),
        },
      });
    } else if (assessment.riskLevel === 'MEDIUM') {
      // For medium risk, just suggest resources (no urgent task)
      results.resources = await suggestResources(studentId, assessment.riskFactors);

      // Create a lower-priority task with longer timeline
      const dueDate = new Date();
      dueDate.setDate(dueDate.getDate() + 7); // 1 week

      const task = await prisma.facilitatorTask.create({
        data: {
          title: `⚠️ Check-in with ${student.firstName} ${student.lastName} (Medium Risk)`,
          description: `Student showing medium risk indicators. Schedule a check-in within the next week to discuss progress and offer support.`,
          dueDate,
          groupId: student.groupId,
          completed: false,
        },
      });

      results.taskId = task.id;
    }

    return results;
  } catch (error) {
    console.error('Error triggering interventions:', error);
    throw error;
  }
}

/**
 * Track intervention effectiveness by comparing outcomes
 */
export async function trackInterventionEffectiveness(
  studentId: string,
  interventionDate: Date
): Promise<{
  riskBefore: string;
  riskAfter: string | null;
  improved: boolean;
  daysElapsed: number;
}> {
  // Find risk profiles before and after intervention
  const profileBefore = await prisma.studentRiskProfile.findFirst({
    where: {
      studentId,
      calculatedAt: {
        lte: interventionDate,
      },
    },
    orderBy: {
      calculatedAt: 'desc',
    },
  });

  const profileAfter = await prisma.studentRiskProfile.findFirst({
    where: {
      studentId,
      calculatedAt: {
        gt: interventionDate,
      },
    },
    orderBy: {
      calculatedAt: 'asc',
    },
  });

  if (!profileBefore) {
    throw new Error('No baseline risk profile found');
  }

  const daysElapsed = profileAfter
    ? Math.floor(
        (new Date(profileAfter.calculatedAt).getTime() -
          interventionDate.getTime()) /
          (1000 * 60 * 60 * 24)
      )
    : 0;

  const riskOrder = { LOW: 0, MEDIUM: 1, HIGH: 2 };
  const improved =
    profileAfter &&
    riskOrder[profileAfter.riskLevel as keyof typeof riskOrder] <
      riskOrder[profileBefore.riskLevel as keyof typeof riskOrder];

  return {
    riskBefore: profileBefore.riskLevel,
    riskAfter: profileAfter?.riskLevel || null,
    improved,
    daysElapsed,
  };
}

/**
 * Generate monthly intervention effectiveness report
 */
export async function generateInterventionReport(
  startDate: Date,
  endDate: Date
): Promise<{
  totalInterventions: number;
  highRiskInterventions: number;
  mediumRiskInterventions: number;
  studentsImproved: number;
  studentsStable: number;
  studentsWorsened: number;
  averageDaysToImprovement: number;
}> {
  // Find all interventions in date range
  const interventions = await prisma.auditLog.findMany({
    where: {
      action: 'AUTO_INTERVENTION_TRIGGERED',
      timestamp: {
        gte: startDate,
        lte: endDate,
      },
    },
  });

  let highRiskCount = 0;
  let mediumRiskCount = 0;
  let improved = 0;
  let stable = 0;
  let worsened = 0;
  let totalDaysToImprovement = 0;
  let improvedCount = 0;

  for (const intervention of interventions) {
    const metadata = JSON.parse(intervention.metadata || '{}');
    
    if (metadata.riskLevel === 'HIGH') {
      highRiskCount++;
    } else if (metadata.riskLevel === 'MEDIUM') {
      mediumRiskCount++;
    }

    // Check if student improved
    try {
      const effectiveness = await trackInterventionEffectiveness(
        metadata.studentId,
        intervention.timestamp
      );

      if (effectiveness.improved) {
        improved++;
        totalDaysToImprovement += effectiveness.daysElapsed;
        improvedCount++;
      } else if (effectiveness.riskAfter === effectiveness.riskBefore) {
        stable++;
      } else {
        worsened++;
      }
    } catch (error) {
      // Student may not have follow-up profile yet
      console.error('Error tracking effectiveness:', error);
    }
  }

  return {
    totalInterventions: interventions.length,
    highRiskInterventions: highRiskCount,
    mediumRiskInterventions: mediumRiskCount,
    studentsImproved: improved,
    studentsStable: stable,
    studentsWorsened: worsened,
    averageDaysToImprovement:
      improvedCount > 0 ? Math.round(totalDaysToImprovement / improvedCount) : 0,
  };
}

export default {
  createCheckInTask,
  notifyCoordinator,
  suggestResources,
  triggerInterventions,
  trackInterventionEffectiveness,
  generateInterventionReport,
};
